apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_HOST: "database-1.cj8oc8ga05ck.us-east-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "database-1"
  DB_NAME: "videodb"
  JWT_SECRET: "mysecretkey"
