apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_HOST: "<RDS-ENDPOINT>"
  DB_USER: "admin"
  DB_PASSWORD: "password"
  DB_NAME: "videodb"
  JWT_SECRET: "mysecretkey"
